### ISSUE TITLE
deployment

### ISSUE THREAD

**Issue by halabuda** [gnarbiz/softwareprops.com#1]
@evanpaschke what do you think about the prospect of setting up a simple auto deploy feature for this repository so we can start putting this domain to good use?

**Comment by evanpaschke** [comment]
@halabuda yep, all for it. just setup another project with circleci, happy to do the same here.

**Comment by halabuda** [comment]
oh you fancy huh. circleci, if you got it like it that, by all means. i was just going to suggest a simple webhook listener but if you want to go the pro route thats fine by me.

**Comment by evanpaschke** [comment]
k, just checked that in https://github.com/softwareprops/softwareprops.com/commit/a4e6634f31be82fe25c46cb6f5e5818eb9ca342d. you should be able to commit a change and have it show up on the site in ~30 sec.

**Comment by halabuda** [comment]
yep just tested, works like a champ. tiiiiiiiite.
